ZGV.Gold.guides_loaded=true
if ZGV:DoMutex("GoldGathC") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Barbed Gill Trout, Spotted Feltail, Zangarian Sporefish")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Furious Crawdad, Golden Darter")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Bloodfin Catfish, Crescent-Tail Skullfish")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Felweed")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Ancient Lichen")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Dreaming Glory")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Nightmare Vine, Fel Lotus")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Mana Thistle")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Netherbloom")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Ragveil")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Terocone")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Adamantite Ore, Eternium Ore")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Adamantite Ore, Eternium Ore, Khorium Ore")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Fel Iron Ore, Eternium Ore")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Knothide Leather")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Thick Clefthoof Leather")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Fel Hide")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Fel Scales")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Nether Dragonscale")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Wind Scales")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Cobra Scales")
